### ISSUE TITLE
this.$original.context is undefined

### ISSUE THREAD

**Issue by BrandonQDixon** [seanvm/fontselect-jquery-plugin#1]
I am getting this error when I attempt to use the plugin.  Relevant code is shown below:

```
<form method="POST">
            <input type="hidden" name="operation" value="changeWebsiteFont">
            <input type="text" name="formFont" id="formFont" value="">
            <input type="submit" value="Submit">
</form>
```

And JS:
`$(function() {
    $("#formFont").fontselect();
}`

The browser says it is in line 333:37 where the error actually occurs (in the non-min JS File).

**Comment by seanvm** [comment]
@BrandonQDixon - in the JS you pasted there is a missing closing parentheses: `$(function() { $("#formFont").fontselect(); })` - Not sure if your actual code is missing it or if it was just a typo

That being said, I haven't been able to recreate this. Are you able to recreate the issue if you load up this page?

```
<!doctype html>
<html>
  <head>
    <title>Jquery Fontselect Example</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="styles/fontselect-default.css" />
    <script src="jquery.fontselect.js"></script>
    <script>
      $(function() { $("#formFont").fontselect(); });
    </script>
  </head>
  <body>
    <form method="POST">
        <input type="hidden" name="operation" value="changeWebsiteFont">
        <input type="text" name="formFont" id="formFont" value="">
        <input type="submit" value="Submit">
    </form>
  </body>
</html>
```

You could also try adding a console.log() on line 331 in the setupHtml() function and see if it is attaching to the correct element.

**Comment by VeronicaPiccone** [comment]
Hi, I have the same problem.
And the and the reason that I'm using jquery 3.1.1 (when I change jquery version with an older one, the error disappears, but I can't use, iin my project, older jquery versions).

How can I fix this issue?

Thanks in advance

**Comment by seanvm** [comment]
Thanks for the additional info @VeronicaPiccone 

This should be fixed in master now.
