### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by andcl** [seanvm/fontselect-jquery-plugin#11]
Hello, 

After initialising the plugin with the following code snippet, I can see the dynamic selector with all the fonts, but when I click any of them, I get the following error:
`Cannot read property 'replace' of null`... The code:

```
$('.font-select').fontselect({
    'style': 'form-control',
    'placeholder': 'Select any font...'
  }).change(function () {
    console.log($(this)); // replace + signs with spaces for css
    var font = $(this).val().replace(/\+/g, ' '); // <---- this line throws the error...
    console.log(font);
  });
```

`console.log($(this))` returns the original select, so the problem is elsewhere. My HTML:

```
...
<select class="form-control font-select" name="font"></select>
...
```

Any ideas? Thanks in advance.

**Comment by seanvm** [comment]
@andcl - Instead of a `select` element you should be using an `input`. Your HTML should look something like this: `<input class="font-select" type="text" />`.  Take a look at [this](https://github.com/seanvm/fontselect-jquery-plugin/blob/master/examples/change.html) for an example.

**Comment by andcl** [comment]
Thanks, @seanvm! Quite obvious, but I did not realise.
