### ISSUE TITLE
moveToSelected doesn't work

### ISSUE THREAD

**Issue by jp26jp** [seanvm/fontselect-jquery-plugin#4]
I wrote this and it works perfectly but I didn't know how you might want it to be integrated into your code which is why I didn't create a pull request:

    var heightOffset;

    $("div.font-select").click(function() {
      $("ul.fs-results").scrollTop(heightOffset);
    });

    $("ul.fs-results li").click(function() {
      heightOffset = this.offsetTop;
    });

**Comment by seanvm** [comment]
Sounds good, I'll take a look at this and your open PR

**Comment by seanvm** [comment]
Thanks for bringing this to my attention. I opted for a slightly different fix in #5 

Feel free to check out my changes and see if they work for your scenario as well.
