### ISSUE TITLE
Only some letter from text change style

### ISSUE THREAD

**Issue by linuxoid** [seanvm/fontselect-jquery-plugin#6]
The fontselect seems to change font type of only some letters from a text, not of the whole text. Do you know why? I simply copied your example.

![screenshot_20180321_231110](https://user-images.githubusercontent.com/239979/37709169-69e3e094-2d5d-11e8-9a6c-223b76762a92.png)

**Comment by seanvm** [comment]
@linuxoid thanks for catching this. It should be fixed now. You can test it out here: https://seanvm.github.io/fontselect-jquery-plugin/examples/change.html
