### ISSUE TITLE
options are not working

### ISSUE THREAD

**Issue by techmRepoAdmin** [seanvm/fontselect-jquery-plugin#7]
not possible to set the options. 
Ex: 
initializing the element with options
$('#font').fontselect({lookahead: 10}); 

but the lookahead still 2 when it is running.

**Comment by seanvm** [comment]
@techmRepoAdmin - This is fixed in the latest release [1.0.5](https://github.com/seanvm/fontselect-jquery-plugin/releases/tag/1.0.5) - Thanks for bringing this to my attention!
